/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author emilio
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public inicio() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pacientebtn = new javax.swing.JButton();
        calendariobtn = new javax.swing.JButton();
        historiaclinicabtn = new javax.swing.JButton();
        plandepagosbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clinica Dental");

        pacientebtn.setBackground(new java.awt.Color(204, 204, 204));
        pacientebtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        pacientebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/person-icon_31846.png"))); // NOI18N
        pacientebtn.setText("Pacientes");
        pacientebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacientebtnMouseClicked(evt);
            }
        });
        pacientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientebtnActionPerformed(evt);
            }
        });

        calendariobtn.setBackground(new java.awt.Color(204, 204, 204));
        calendariobtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        calendariobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendar-icon_31857.png"))); // NOI18N
        calendariobtn.setText("Calendario");
        calendariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendariobtnActionPerformed(evt);
            }
        });

        historiaclinicabtn.setBackground(new java.awt.Color(204, 204, 204));
        historiaclinicabtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        historiaclinicabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/name-card-icon_31834.png"))); // NOI18N
        historiaclinicabtn.setText("Historia Clinica");
        historiaclinicabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaclinicabtnActionPerformed(evt);
            }
        });

        plandepagosbtn.setBackground(new java.awt.Color(204, 204, 204));
        plandepagosbtn.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        plandepagosbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/money-icon.png"))); // NOI18N
        plandepagosbtn.setText("Plan de Pagos");
        plandepagosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plandepagosbtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/information-1481584_960_720.png"))); // NOI18N
        jButton1.setText("Informacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pacientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(plandepagosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(historiaclinicabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calendariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pacientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(plandepagosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(historiaclinicabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientebtnMouseClicked

        
    }//GEN-LAST:event_pacientebtnMouseClicked

    private void pacientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientebtnActionPerformed
    this.dispose();
    EdicionPacientes v = new EdicionPacientes();
    v.setVisible(true);
    }//GEN-LAST:event_pacientebtnActionPerformed

    private void plandepagosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plandepagosbtnActionPerformed
        this.dispose();
    PlanDePagos v = new PlanDePagos();
    v.setVisible(true);
    }//GEN-LAST:event_plandepagosbtnActionPerformed

    private void historiaclinicabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaclinicabtnActionPerformed
        this.dispose();
        historiaclinica v = new historiaclinica();
        v.setVisible(true);
    }//GEN-LAST:event_historiaclinicabtnActionPerformed

    private void calendariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendariobtnActionPerformed
        this.dispose();
        calendario v = new calendario();
        v.setVisible(true);
        
    }//GEN-LAST:event_calendariobtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        information v = new information();
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
            new inicio().setVisible(true);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calendariobtn;
    private javax.swing.JButton historiaclinicabtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pacientebtn;
    private javax.swing.JButton plandepagosbtn;
    // End of variables declaration//GEN-END:variables
}
