/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author emilio
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pacientebtn = new javax.swing.JButton();
        calendariobtn = new javax.swing.JButton();
        historiaclinicabtn = new javax.swing.JButton();
        plandepagosbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("WhatnotW00-Regular", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clinica Dental");

        pacientebtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        pacientebtn.setText("Pacientes");
        pacientebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pacientebtnMouseClicked(evt);
            }
        });
        pacientebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientebtnActionPerformed(evt);
            }
        });

        calendariobtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        calendariobtn.setText("Calendario");
        calendariobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendariobtnActionPerformed(evt);
            }
        });

        historiaclinicabtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        historiaclinicabtn.setText("Historia Clinica");
        historiaclinicabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaclinicabtnActionPerformed(evt);
            }
        });

        plandepagosbtn.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        plandepagosbtn.setText("Plan de Pagos");
        plandepagosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plandepagosbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pacientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(plandepagosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(historiaclinicabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(calendariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pacientebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plandepagosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(historiaclinicabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendariobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientebtnMouseClicked

        
    }//GEN-LAST:event_pacientebtnMouseClicked

    private void pacientebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientebtnActionPerformed
    
    pacientes vp = new pacientes();
    vp.setVisible(true);
    }//GEN-LAST:event_pacientebtnActionPerformed

    private void plandepagosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plandepagosbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plandepagosbtnActionPerformed

    private void historiaclinicabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaclinicabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historiaclinicabtnActionPerformed

    private void calendariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendariobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendariobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calendariobtn;
    private javax.swing.JButton historiaclinicabtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pacientebtn;
    private javax.swing.JButton plandepagosbtn;
    // End of variables declaration//GEN-END:variables
}
